version: '3.7'

services:
  consul-server:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: consul agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 --data-dir /consul/data
    networks:
      - consul
    # volumes:
    #   - ./consul-data-server:/consul/data

  meili-0:
    image: meili-img:latest
    container_name: meili-0
    restart: always
    command: "sh -c '/bin/consul agent -client=0.0.0.0 -node=client-0 -retry-join=consul-server --data-dir /consul/data & meilisearch'"
    networks:
      - consul
    # volumes:
    #   - ./consul-data-client:/consul/data

  meili-1:
    image: meili-img:latest
    container_name: meili-1
    restart: always
    command: "sh -c '/bin/consul agent -client=0.0.0.0 -node=client-1 -retry-join=consul-server --data-dir /consul/data & meilisearch'"
    networks:
      - consul
    # volumes:
    #   - ./consul-data-client:/consul/data

networks:
  consul:
    driver: bridge
