[sources.generate_syslog]
type = "demo_logs"
interval = 0.0001
format = "syslog"

[transforms.parse_syslog_tfs]
type = "remap"
inputs = ["generate_syslog"]
source = ". |= parse_syslog!(.message)"

[transforms.filter_syslog_errors]
type = "filter"
inputs = ["parse_syslog_tfs"]
condition = '.severity != "info" || .severity != "debug"'

[transforms.rename_key]
type = "remap"
inputs = ["filter_syslog_errors"]
source = ".id = del(.msgid)"

[sinks.emit_http]
type = "http"
inputs = [ "rename_key" ]
uri =  "http://localhost:3000/logs"
encoding = { codec = "json" }
method = "post"
batch = { max_bytes = 2048, max_events = 10, timeout_secs = 0.01 }

# [sinks.sysout_sink]
# type = "console"
# inputs = ["rename_key"]
# encoding = { codec = "json" }
