[sources.generate_syslog]
type = "demo_logs"
format = "syslog"
count = 100

[transforms.parse_syslog_tfs]
type = "remap"
inputs = ["generate_syslog"]
source = ". |= parse_syslog!(.message)"

[transforms.filter_syslog_errors]
type = "filter"
inputs = ["parse_syslog_tfs"]
condition = '.severity != "info" || .severity != "debug"'

[transforms.rename_key]
type = "remap"
inputs = ["filter_syslog_errors"]
source = ".id = del(.msgid)"

[sinks.emit_http]
type = "http"
inputs = [ "rename_key" ]
uri =  "http://localhost:3000/logs"
encoding = { codec = "json" }
method = "post"

# [sinks.sysout_sink]
# type = "console"
# inputs = ["rename_key"]
# encoding = { codec = "json" }
